[metadata]
name = finquery_parser
version = 0.1.0
author = Your Name
author_email = your.email@example.com
description = A library for parsing, cleaning, and chunking financial 10-K documents.
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find:
python_requires = >=3.11
install_requires =
    langfuse
    langchain_chroma
    langchain_core
    langchain
    langchain_huggingface
    pydantic
    chromadb
    unstructured
    bs4